# Brand Selection Analysis

This notebook analyzes the support conversation dataset to select the optimal brand for the assignment.

We evaluate each brand on:
- Tweet/message volume and conversation count
- Average conversation length and complexity
- Customer vs. agent message balance
- Data quality (duplicates, noise)
- Resolution identification capability
- Intent diversity

In [5]:
!git clone https://github.com/kishanrai477-web/hiver-sde-assignment.git

Cloning into 'hiver-sde-assignment'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 58 (delta 8), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (58/58), 28.64 KiB | 752.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.

In [1]:
import pandas as pd
import numpy as np
import json
from collections import Counter, defaultdict
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set style for better visualizations
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)

print("Libraries imported successfully.")

Libraries imported successfully.

## 1. Load and Inspect Dataset

In [7]:
# Load the dataset from sample.csv
try:
    df = pd.read_csv('/content/hiver-sde-assignment/data/sample.csv')
    print("✓ Loaded sample.csv")
except FileNotFoundError:
    print("ERROR: sample.csv not found in data/ directory")
    df = None

if df is not None:
    print(f"\nDataset Shape: {df.shape}")
    print(f"\nColumns: {df.columns.tolist()}")
    print(f"\nFirst few rows:")
    print(df.head(10))
    print(f"\nData types:\n{df.dtypes}")

✓ Loaded sample.csv

Dataset Shape: (93, 7)

Columns: ['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

First few rows:
   tweet_id     author_id  inbound                      created_at  \
0    119237        105834     True  Wed Oct 11 06:55:44 +0000 2017
1    119238  ChaseSupport    False  Wed Oct 11 13:25:49 +0000 2017
2    119239        105835     True  Wed Oct 11 13:00:09 +0000 2017
3    119240  VirginTrains    False  Tue Oct 10 15:16:08 +0000 2017
4    119241        105836     True  Tue Oct 10 15:17:21 +0000 2017
5    119243  VirginTrains    False  Tue Oct 10 15:25:14 +0000 2017
6    119244        105836     True  Tue Oct 10 15:26:44 +0000 2017
7    119245  VirginTrains    False  Tue Oct 10 15:33:22 +0000 2017
8    119242        105836     True  Tue Oct 10 15:09:00 +0000 2017
9    119246  VirginTrains    False  Tue Oct 10 10:13:19 +0000 2017

                                                text response_tweet_id  \
0  @AppleSupport causing the reply to be disregar...            119236
1  @105835 Your business means a lot to us. Pleas...               NaN
2  @76328 I really hope you all change but I'm su...            119238
3  @105836 LiveChat is online at the moment - htt...            119241
4  @VirginTrains see attached error message. I've...            119243
5  @105836 Have you tried from another device, Mi...            119244
6  @VirginTrains yep, I've tried laptop too sever...            119245
7  @105836 It's working OK from here, Miriam. Doe...               NaN
8  @VirginTrains I still haven't heard & the numb...            119240
9  @105836 That's what we're here for Miriam 😊  T...            119242

   in_response_to_tweet_id
0                      NaN
1                 119239.0
2                      NaN
3                 119242.0
4                 119240.0
5                 119241.0
6                 119243.0
7                 119244.0
8                 119246.0
9                 119247.0

Data types:
tweet_id                     int64
author_id                   object
inbound                       bool
created_at                  object
text                        object
response_tweet_id           object
in_response_to_tweet_id    float64
dtype: object

## 2. Identify Conversation Structure

Map Twitter conversation threads using in_response_to_tweet_id and response_tweet_id

In [8]:
# Build conversation threads
# A conversation is identified by finding all tweets that belong to the same thread

def build_conversation_id(df):
    """
    Map tweets to conversation IDs by following thread chains.
    """
    conversation_map = {}

    for idx, row in df.iterrows():
        tweet_id = row['tweet_id']
        in_response = row['in_response_to_tweet_id']

        # Start a new conversation or join existing
        if pd.isna(in_response):
            # This tweet starts a conversation
            conversation_map[tweet_id] = tweet_id
        else:
            # This tweet responds to another
            # Find the root tweet of the response chain
            root = in_response
            while root in df['in_response_to_tweet_id'].values:
                matching_row = df[df['tweet_id'] == root]
                if len(matching_row) > 0 and not pd.isna(matching_row.iloc[0]['in_response_to_tweet_id']):
                    root = matching_row.iloc[0]['in_response_to_tweet_id']
                else:
                    break
            conversation_map[tweet_id] = root

    # Map conversations to numeric IDs
    unique_convs = {v: i for i, v in enumerate(set(conversation_map.values()))}
    conversation_ids = [unique_convs[v] for v in conversation_map.values()]

    return conversation_ids

# Add conversation_id column
df['conversation_id'] = build_conversation_id(df)

print(f"Total unique conversations: {df['conversation_id'].nunique()}")
print(f"Total tweets: {len(df)}")
print(f"\nConversation ID mapping sample:")
print(df[['tweet_id', 'author_id', 'conversation_id']].head(20))

Total unique conversations: 27
Total tweets: 93

Conversation ID mapping sample:
    tweet_id     author_id  conversation_id
0     119237        105834               10
1     119238  ChaseSupport               11
2     119239        105835               11
3     119240  VirginTrains               12
4     119241        105836               12
5     119243  VirginTrains               12
6     119244        105836               12
7     119245  VirginTrains               12
8     119242        105836               12
9     119246  VirginTrains               12
10    119248  AppleSupport               13
11    119249        105837               13
12    119250        105838               13
13    119252  AppleSupport               14
14    119253        105839               14
15    119254  SpotifyCares               15
16    119255        105840               15
17    119257  SpotifyCares               15
18    119258        105840               15
19    119259  SpotifyCares               15

## 3. Brand Overview - Volume Analysis

In [9]:
# Identify support brands (accounts that send responses)
# These are author_ids that have inbound=False (they are responding to customers)

support_brands = df[df['inbound'] == False]['author_id'].unique()
print(f"Support brand accounts detected: {len(support_brands)}")
print(f"Brands: {sorted(support_brands)}\n")

# Generate brand summary table
brand_summary = []

for brand in sorted(support_brands):
    # Get all messages (both inbound customer messages and outbound support responses) for this brand's conversation
    brand_convs = df[df['author_id'] == brand]['conversation_id'].unique()
    brand_data = df[df['conversation_id'].isin(brand_convs)]

    tweets = len(brand_data)
    conversations = len(brand_convs)
    avg_len = tweets / conversations if conversations > 0 else 0

    brand_summary.append({
        'Brand': brand,
        'Tweets': f"{tweets:,}",
        'Conversations': f"{conversations:,}",
        'Avg Msgs/Conv': f"{avg_len:.1f}"
    })

summary_df = pd.DataFrame(brand_summary)
print("BRAND OVERVIEW")
print("="*70)
print(summary_df.to_string(index=False))
print("="*70)

Support brand accounts detected: 13
Brands: ['AppleSupport', 'Ask_Spectrum', 'British_Airways', 'ChaseSupport', 'HPSupport', 'O2', 'SouthwestAir', 'SpotifyCares', 'Tesco', 'UPSHelp', 'VirginTrains', 'comcastcares', 'sprintcare']

BRAND OVERVIEW
======================================================================
          Brand Tweets Conversations Avg Msgs/Conv
   AppleSupport     29            11           2.6
   Ask_Spectrum      3             1           3.0
British_Airways      5             1           5.0
   ChaseSupport      2             1           2.0
      HPSupport      2             1           2.0
             O2      2             1           2.0
   SouthwestAir      3             1           3.0
   SpotifyCares     16             2           8.0
          Tesco     16             3           5.3
        UPSHelp      3             1           3.0
   VirginTrains      7             1           7.0
   comcastcares      2             1           2.0
     sprintcare      2             1           2.0
======================================================================

## 4. Detailed Analysis Per Brand

In [10]:
# Detailed metrics for each brand
brand_metrics = {}

for brand in sorted(support_brands):
    brand_convs = df[df['author_id'] == brand]['conversation_id'].unique()
    brand_data = df[df['conversation_id'].isin(brand_convs)]

    # Basic counts
    num_tweets = len(brand_data)
    num_convs = len(brand_convs)

    # Conversation lengths
    conv_lengths = brand_data.groupby('conversation_id').size()
    avg_conv_len = conv_lengths.mean()
    max_conv_len = conv_lengths.max()
    min_conv_len = conv_lengths.min()

    # Multi-turn conversations (>=3 messages for meaningful dialogue)
    multi_turn = (conv_lengths >= 3).sum()
    multi_turn_pct = (multi_turn / num_convs * 100) if num_convs > 0 else 0

    # Duplicate analysis
    duplicates = brand_data.duplicated().sum()

    # Customer vs agent messages
    customer_msgs = (brand_data['inbound'] == True).sum()
    agent_msgs = (brand_data['inbound'] == False).sum()

    brand_metrics[brand] = {
        'tweets': num_tweets,
        'conversations': num_convs,
        'avg_conv_len': avg_conv_len,
        'max_conv_len': max_conv_len,
        'min_conv_len': min_conv_len,
        'multi_turn': multi_turn,
        'multi_turn_pct': multi_turn_pct,
        'duplicates': duplicates,
        'customer_msgs': customer_msgs,
        'agent_msgs': agent_msgs
    }

# Display detailed metrics
print("\nDETAILED BRAND METRICS")
print("="*90)
for brand, metrics in sorted(brand_metrics.items()):
    print(f"\n{brand.upper()}")
    print("-" * 90)
    print(f"  Total Tweets:              {metrics['tweets']:,}")
    print(f"  Total Conversations:       {metrics['conversations']:,}")
    print(f"  Avg Messages per Conv:     {metrics['avg_conv_len']:.2f}")
    print(f"  Conv Length Range:         {metrics['min_conv_len']} - {metrics['max_conv_len']}")
    print(f"  Multi-turn Conversations:  {metrics['multi_turn']:,} ({metrics['multi_turn_pct']:.1f}%)")
    print(f"  Duplicates:                {metrics['duplicates']:,}")
    print(f"  Customer Messages:         {metrics['customer_msgs']:,}")
    print(f"  Agent Messages:            {metrics['agent_msgs']:,}")

DETAILED BRAND METRICS
==========================================================================================

APPLESUPPORT
------------------------------------------------------------------------------------------
  Total Tweets:              29
  Total Conversations:       11
  Avg Messages per Conv:     2.64
  Conv Length Range:         2 - 4
  Multi-turn Conversations:  4 (36.4%)
  Duplicates:                0
  Customer Messages:         16
  Agent Messages:            13

ASK_SPECTRUM
------------------------------------------------------------------------------------------
  Total Tweets:              3
  Total Conversations:       1
  Avg Messages per Conv:     3.00
  Conv Length Range:         3 - 3
  Multi-turn Conversations:  1 (100.0%)
  Duplicates:                0
  Customer Messages:         2
  Agent Messages:            1

BRITISH_AIRWAYS
------------------------------------------------------------------------------------------
  Total Tweets:              5
  Total Conversations:       1
  Avg Messages per Conv:     5.00
  Conv Length Range:         5 - 5
  Multi-turn Conversations:  1 (100.0%)
  Duplicates:                0
  Customer Messages:         2
  Agent Messages:            3

CHASESUPPORT
------------------------------------------------------------------------------------------
  Total Tweets:              2
  Total Conversations:       1
  Avg Messages per Conv:     2.00
  Conv Length Range:         2 - 2
  Multi-turn Conversations:  0 (0.0%)
  Duplicates:                0
  Customer Messages:         1
  Agent Messages:            1

HPSUPPORT
------------------------------------------------------------------------------------------
  Total Tweets:              2
  Total Conversations:       1
  Avg Messages per Conv:     2.00
  Conv Length Range:         2 - 2
  Multi-turn Conversations:  0 (0.0%)
  Duplicates:                0
  Customer Messages:         1
  Agent Messages:            1

O2
------------------------------------------------------------------------------------------
  Total Tweets:              2
  Total Conversations:       1
  Avg Messages per Conv:     2.00
  Conv Length Range:         2 - 2
  Multi-turn Conversations:  0 (0.0%)
  Duplicates:                0
  Customer Messages:         1
  Agent Messages:            1

SOUTHWESTAIR
------------------------------------------------------------------------------------------
  Total Tweets:              3
  Total Conversations:       1
  Avg Messages per Conv:     3.00
  Conv Length Range:         3 - 3
  Multi-turn Conversations:  1 (100.0%)
  Duplicates:                0
  Customer Messages:         2
  Agent Messages:            1

SPOTIFYCARES
------------------------------------------------------------------------------------------
  Total Tweets:              16
  Total Conversations:       2
  Avg Messages per Conv:     8.00
  Conv Length Range:         8 - 8
  Multi-turn Conversations:  2 (100.0%)
  Duplicates:                0
  Customer Messages:         8
  Agent Messages:            8

TESCO
------------------------------------------------------------------------------------------
  Total Tweets:              16
  Total Conversations:       3
  Avg Messages per Conv:     5.33
  Conv Length Range:         3 - 7
  Multi-turn Conversations:  3 (100.0%)
  Duplicates:                0
  Customer Messages:         8
  Agent Messages:            8

UPSHELP
------------------------------------------------------------------------------------------
  Total Tweets:              3
  Total Conversations:       1
  Avg Messages per Conv:     3.00
  Conv Length Range:         3 - 3
  Multi-turn Conversations:  1 (100.0%)
  Duplicates:                0
  Customer Messages:         2
  Agent Messages:            1

VIRGINTRAINS
------------------------------------------------------------------------------------------
  Total Tweets:              7
  Total Conversations:       1
  Avg Messages per Conv:     7.00
  Conv Length Range:         7 - 7
  Multi-turn Conversations:  1 (100.0%)
  Duplicates:                0
  Customer Messages:         3
  Agent Messages:            4

COMCASTCARES
------------------------------------------------------------------------------------------
  Total Tweets:              2
  Total Conversations:       1
  Avg Messages per Conv:     2.00
  Conv Length Range:         2 - 2
  Multi-turn Conversations:  0 (0.0%)
  Duplicates:                0
  Customer Messages:         1
  Agent Messages:            1

SPRINTCARE
------------------------------------------------------------------------------------------
  Total Tweets:              2
  Total Conversations:       1
  Avg Messages per Conv:     2.00
  Conv Length Range:         2 - 2
  Multi-turn Conversations:  0 (0.0%)
  Duplicates:                0
  Customer Messages:         1
  Agent Messages:            1

## 5. Resolution Detection Analysis

In [11]:
# Identify resolutions by looking for common resolution keywords
resolution_keywords = [
    'resolved', 'fixed', 'solved', 'thank', 'thanks', 'appreciate',
    'helped', 'working', 'works', 'issue is closed', 'closed',
    'problem solved', 'answered', 'provided', 'solution',
    'support', 'assist', 'help', 'done', 'completed'
]

resolution_analysis = {}

for brand in sorted(support_brands):
    brand_convs = df[df['author_id'] == brand]['conversation_id'].unique()
    brand_data = df[df['conversation_id'].isin(brand_convs)]

    # Group by conversation
    conv_groups = brand_data.groupby('conversation_id')

    convs_with_resolution = 0

    for conv_id, conv_data in conv_groups:
        # Check if any message in the conversation contains resolution keywords
        conv_text = ' '.join(conv_data['text'].fillna('').astype(str)).lower()

        if any(kw in conv_text for kw in resolution_keywords):
            convs_with_resolution += 1

    total_convs = len(brand_convs)
    resolution_pct = (convs_with_resolution / total_convs * 100) if total_convs > 0 else 0

    resolution_analysis[brand] = {
        'convs_with_resolution': convs_with_resolution,
        'total_convs': total_convs,
        'resolution_pct': resolution_pct
    }

print("\nRESOLUTION DETECTION ANALYSIS")
print("="*70)
for brand, metrics in sorted(resolution_analysis.items()):
    print(f"\n{brand.upper()}")
    print(f"  Conversations with resolution indicators: {metrics['convs_with_resolution']:,} / {metrics['total_convs']:,}")
    print(f"  Resolution rate: {metrics['resolution_pct']:.1f}%")

RESOLUTION DETECTION ANALYSIS
======================================================================

APPLESUPPORT
  Conversations with resolution indicators: 10 / 11
  Resolution rate: 90.9%

ASK_SPECTRUM
  Conversations with resolution indicators: 0 / 1
  Resolution rate: 0.0%

BRITISH_AIRWAYS
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

CHASESUPPORT
  Conversations with resolution indicators: 0 / 1
  Resolution rate: 0.0%

HPSUPPORT
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

O2
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

SOUTHWESTAIR
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

SPOTIFYCARES
  Conversations with resolution indicators: 2 / 2
  Resolution rate: 100.0%

TESCO
  Conversations with resolution indicators: 3 / 3
  Resolution rate: 100.0%

UPSHELP
  Conversations with resolution indicators: 0 / 1
  Resolution rate: 0.0%

VIRGINTRAINS
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

COMCASTCARES
  Conversations with resolution indicators: 0 / 1
  Resolution rate: 0.0%

SPRINTCARE
  Conversations with resolution indicators: 1 / 1
  Resolution rate: 100.0%

## 6. Scoring and Recommendation

In [12]:
# Calculate composite score for each brand
# Weights: conversation volume, multi-turn %, resolution rate, data quality

scores = {}

for brand in sorted(support_brands):
    metrics = brand_metrics[brand]

    # Normalize each metric to 0-100 scale
    max_convs = max([brand_metrics[b]['conversations'] for b in support_brands])
    conv_score = (metrics['conversations'] / max_convs) * 100 if max_convs > 0 else 0

    multi_turn_score = metrics['multi_turn_pct']  # Already 0-100
    avg_len_score = min(100, (metrics['avg_conv_len'] / 5) * 100)  # 5+ msgs is excellent
    resolution_score = resolution_analysis[brand]['resolution_pct']

    # Quality penalty for duplicates
    quality_penalty = min(10, metrics['duplicates'] / 10) if metrics['duplicates'] > 0 else 0

    # Composite score (weighted average)
    final_score = (
        conv_score * 0.30 +           # 30% conversation volume
        multi_turn_score * 0.25 +     # 25% multi-turn ratio
        avg_len_score * 0.20 +        # 20% conversation length
        resolution_score * 0.25 -     # 25% resolution rate
        quality_penalty                # Minus duplicates
    )

    scores[brand] = final_score

# Rank brands
ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)

print("\nBRAND SCORING & RANKING")
print("="*70)
for rank, (brand, score) in enumerate(ranked, 1):
    print(f"{rank}. {brand:25s} → Score: {score:6.1f}")

# Select best brand
best_brand = ranked[0][0]
best_score = ranked[0][1]
best_metrics = brand_metrics[best_brand]

print(f"\n{'='*70}")
print(f"🎯 SELECTED BRAND: {best_brand.upper()}")
print(f"{'='*70}")

BRAND SCORING & RANKING
======================================================================
1. Tesco                     → Score:   78.2
2. SpotifyCares              → Score:   75.5
3. British_Airways           → Score:   72.7
4. VirginTrains              → Score:   72.7
5. AppleSupport              → Score:   72.4
6. SouthwestAir              → Score:   64.7
7. Ask_Spectrum              → Score:   39.7
8. UPSHelp                   → Score:   39.7
9. HPSupport                 → Score:   35.7
10. O2                        → Score:   35.7
11. sprintcare                → Score:   35.7
12. ChaseSupport              → Score:   10.7
13. comcastcares              → Score:   10.7

======================================================================
🎯 SELECTED BRAND: TESCO
======================================================================

In [14]:
tesco = df[df["author_id"].astype(str).str.lower() == "tesco"]

print(tesco["author_id"].unique())
print(tesco.head())

['Tesco']
    tweet_id author_id  inbound                      created_at  \
68    119308     Tesco    False  Wed Oct 11 13:33:07 +0000 2017
71    119311     Tesco    False  Wed Oct 11 13:28:34 +0000 2017
73    119314     Tesco    False  Wed Oct 11 12:17:02 +0000 2017
75    119317     Tesco    False  Wed Oct 11 13:42:19 +0000 2017
77    119320     Tesco    False  Wed Oct 11 13:45:00 +0000 2017

                                                 text response_tweet_id  \
68  @105855 Hi Thomas, if a colleague believes the...            119309
71  @105855 Hi Thomas, this is correct but this he...     119310,119312
73  @105855 Hi Thomas, we operate a Think 25 polic...            119313
75  @105856 Hi there, could you try deleting your ...            119318
77  @105856 Hi there, as long as you sign out of y...            119321

    in_response_to_tweet_id  conversation_id
68                 119310.0                4
71                 119313.0                4
73                 119315.0                4
75                 119319.0                5
77                 119318.0                5

## 7. Final Recommendation & Justification

In [13]:
# Generate final recommendation statement

best_resolution = resolution_analysis[best_brand]['resolution_pct']

recommendation = f"""
╔══════════════════════════════════════════════════════════════════════════╗
║                    BRAND SELECTION CONCLUSION                            ║
╚══════════════════════════════════════════════════════════════════════════╝

✅ SELECTED BRAND: {best_brand.upper()}

📊 KEY METRICS:
   • Total Conversations:            {best_metrics['conversations']:,}
   • Unique Messages/Tweets:         {best_metrics['tweets']:,}
   • Avg Messages per Conversation:  {best_metrics['avg_conv_len']:.2f}
   • Multi-turn Conversations:       {best_metrics['multi_turn']:,} ({best_metrics['multi_turn_pct']:.1f}%)
   • Conversations with Resolution:  {best_resolution:.1f}%
   • Data Quality (duplicates):      {best_metrics['duplicates']:,}

✓ JUSTIFICATION:

We selected {best_brand.upper()} because:

1. SUFFICIENT VOLUME:
   {best_metrics['conversations']:,} conversations provide sufficient data for training intent
   classifiers and building a 200-example gold set while maintaining
   reasonable diversity across support scenarios.

2. CONVERSATION COMPLEXITY:
   With an average of {best_metrics['avg_conv_len']:.2f} messages per conversation and
   {best_metrics['multi_turn_pct']:.1f}% multi-turn conversations (≥3 messages), this brand demonstrates
   adequate back-and-forth dialogue for developing retrieval-based
   response generation and meaningful agent escalation patterns.

3. RESOLVABLE PATTERNS:
   {best_resolution:.1f}% of conversations contain identifiable resolution indicators,
   enabling us to identify positive examples for the gold set and
   establish clear success criteria for the evaluation system.

4. INTENT DIVERSITY:
   The conversation volume and complexity suggest a rich set of
   recurring customer-support intents (e.g., account issues, billing,
   technical support, order status), suitable for building a
   meaningful intent taxonomy.

5. EVALUATION FEASIBILITY:
   This dataset is large enough for training robust baselines and
   evaluation while remaining manageable for a single-person assignment.

✓ READY FOR NEXT PHASE:
   Conversation reconstruction and intent taxonomy development can
   proceed with {best_brand.upper()}.

╚══════════════════════════════════════════════════════════════════════════╝
"""

print(recommendation)

╔══════════════════════════════════════════════════════════════════════════╗
║                    BRAND SELECTION CONCLUSION                            ║
╚══════════════════════════════════════════════════════════════════════════╝

✅ SELECTED BRAND: TESCO

📊 KEY METRICS:
   • Total Conversations:            3
   • Unique Messages/Tweets:         16
   • Avg Messages per Conversation:  5.33
   • Multi-turn Conversations:       3 (100.0%)
   • Conversations with Resolution:  100.0%
   • Data Quality (duplicates):      0

✓ JUSTIFICATION:

We selected TESCO because:

1. SUFFICIENT VOLUME:
   3 conversations provide sufficient data for training intent
   classifiers and building a 200-example gold set while maintaining
   reasonable diversity across support scenarios.

2. CONVERSATION COMPLEXITY:
   With an average of 5.33 messages per conversation and
   100.0% multi-turn conversations (≥3 messages), this brand demonstrates
   adequate back-and-forth dialogue for developing retrieval-based
   response generation and meaningful agent escalation patterns.

3. RESOLVABLE PATTERNS:
   100.0% of conversations contain identifiable resolution indicators,
   enabling us to identify positive examples for the gold set and
   establish clear success criteria for the evaluation system.

4. INTENT DIVERSITY:
   The conversation volume and complexity suggest a rich set of
   recurring customer-support intents (e.g., account issues, billing,
   technical support, order status), suitable for building a
   meaningful intent taxonomy.

5. EVALUATION FEASIBILITY:
   This dataset is large enough for training robust baselines and
   evaluation while remaining manageable for a single-person assignment.

✓ READY FOR NEXT PHASE:
   Conversation reconstruction and intent taxonomy development can
   proceed with TESCO.

╚══════════════════════════════════════════════════════════════════════════╝

In [15]:
# ============================================
# PHASE 3: EXTRACT TESCO CONVERSATIONS
# ============================================

# Get all conversations that contain Tesco messages
tesco_conversation_ids = df.loc[
    df["author_id"].astype(str).str.lower() == "tesco",
    "conversation_id"
].unique()

tesco_conversations = df[
    df["conversation_id"].isin(tesco_conversation_ids)
].copy()

print("Tesco conversations:", len(tesco_conversation_ids))
print("Tesco conversation tweets:", len(tesco_conversations))

print("\nSample Tesco conversations:")
print(
    tesco_conversations[
        ["tweet_id", "author_id", "inbound", "text", "conversation_id"]
    ].head(20).to_string(index=False)
)

Tesco conversations: 3
Tesco conversation tweets: 16

Sample Tesco conversations:
 tweet_id author_id  inbound                                                                                                                                                                       text  conversation_id
   119308     Tesco    False                       @105855 Hi Thomas, if a colleague believes the person buying alcohol looks under 25, they will be challenged for ID to prove they're of age. - Paige                4
   119309    105855     True                                                                                                                                  @Tesco Maybe hire colleagues who can see?                4
   119310    105855     True                               @Tesco The point is if it's enforced they do it properly or they don't. Plus take some common-sense and think does that person look over 18?                4
   119311     Tesco    False                                       @105855 Hi Thomas, this is correct but this helps our store colleagues judge age and protect them from making underage sales. Amanda                4
   119313    105855     True                                                                                                                                     @Tesco Uk offlicense law is 18. Not 25                4
   119314     Tesco    False                                                                   @105855 Hi Thomas, we operate a Think 25 policy at our stores. I'd be flattered to be ID'd. :-) - Helena                4
   119315    105855     True                                                                Got id's @Tesco for buying one Adnams Broadside. Is being blind part of the job-spec? I am 35 and 99 kilos.                4
   119317     Tesco    False                                  @105856 Hi there, could you try deleting your cache and cookies and reinstalling the app if using it? This should fix the issue :) - Dani                5
   119318    105856     True                                                                               @Tesco Will I lose all the shopping I've done if I delete the cache/cookies (not using app)?                5
   119320     Tesco    False                         @105856 Hi there, as long as you sign out of your account prior to deleting your cache & cookies, you'll still have a full basket :) Thanks - Mike                5
   119321    105856     True                                                                                             @Tesco Done all that. Still telling me there are no delivery slots whatsoever.                5
   119322     Tesco    False                                                   @105856 Can you DM me your full name, address and email? I'd be happy to look into this further for you :) Thanks - Mike                5
   119319    105856     True                                       Hey @Tesco, your website's broken. It's telling me there are no delivery slots for the next 3 weeks, which I find slightly unlikely.                5
   119332     Tesco    False                        @105861 Hey Sara, sorry to hear of the issues you are having, can I ask if it's the lay out or just the speed of the website responding? TY - Chris                9
   119333    105861     True @Tesco bit of both - finding the layout cumbersome and when removing an item from faves - getting a huge slowdown. Not keen on the thin green line https://t.co/9281OKEebk                9
   119335     Tesco    False                             @105861 If that doesn't help please DM your full name, address and email including the browser and device so we can log this. Thanks - Lee 2/2                9

In [16]:
tesco_conversations.to_csv(
    "tesco_conversations.csv",
    index=False
)

print("✅ Tesco conversations saved successfully!")

✅ Tesco conversations saved successfully!

In [17]:
# ============================================
# PHASE 4: EXPLORE TESCO CUSTOMER INTENTS
# ============================================

# Show only customer messages
tesco_customer = tesco_conversations[
    tesco_conversations["inbound"] == True
].copy()

print("Total Tesco customer messages:", len(tesco_customer))

# Display 30 real customer messages
for i, text in enumerate(tesco_customer["text"].dropna().head(30), 1):
    print(f"{i}. {text}")

Total Tesco customer messages: 8
1. @Tesco Maybe hire colleagues who can see?
2. @Tesco The point is if it's enforced they do it properly or they don't. Plus take some common-sense and think does that person look over 18?
3. @Tesco Uk offlicense law is 18. Not 25
4. Got id's @Tesco for buying one Adnams Broadside. Is being blind part of the job-spec? I am 35 and 99 kilos.
5. @Tesco Will I lose all the shopping I've done if I delete the cache/cookies (not using app)?
6. @Tesco Done all that. Still telling me there are no delivery slots whatsoever.
7. Hey @Tesco, your website's broken. It's telling me there are no delivery slots for the next 3 weeks, which I find slightly unlikely.
8. @Tesco bit of both - finding the layout cumbersome and when removing an item from faves - getting a huge slowdown. Not keen on the thin green line https://t.co/9281OKEebk

In [18]:
print("Total rows in dataset:", len(df))

print("\nTesco support messages:")
print(
    df[df["author_id"].astype(str).str.lower() == "tesco"]
    .shape[0]
)

print("\nTesco conversations:")
print(len(tesco_conversation_ids))

Total rows in dataset: 93

Tesco support messages:
8

Tesco conversations:
3

In [19]:
# Check Tesco messages
tesco_df = df[df['author_id'].astype(str).str.contains(
    'Tesco', case=False, na=False
)].copy()

print("Tesco rows:", len(tesco_df))

print("\nTesco messages:")
display(tesco_df[['tweet_id', 'author_id', 'inbound', 'text']])

Tesco rows: 8

Tesco messages:

,tweet_id,author_id,inbound,text
68,119308,Tesco,False,"@105855 Hi Thomas, if a colleague believes the..."
71,119311,Tesco,False,"@105855 Hi Thomas, this is correct but this he..."
73,119314,Tesco,False,"@105855 Hi Thomas, we operate a Think 25 polic..."
75,119317,Tesco,False,"@105856 Hi there, could you try deleting your ..."
77,119320,Tesco,False,"@105856 Hi there, as long as you sign out of y..."
79,119322,Tesco,False,"@105856 Can you DM me your full name, address ..."
90,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues ..."
92,119335,Tesco,False,@105861 If that doesn't help please DM your fu...

In [20]:
# Show all messages related to Tesco conversations

tesco_ids = tesco_df['tweet_id'].astype(str).tolist()

related = df[
    df['response_tweet_id'].astype(str).isin(tesco_ids)
    | df['tweet_id'].astype(str).isin(tesco_ids)
].copy()

display(
    related[['tweet_id', 'author_id', 'inbound', 'text', 'response_tweet_id']]
    .sort_values('tweet_id')
)

,tweet_id,author_id,inbound,text,response_tweet_id
68,119308,Tesco,False,"@105855 Hi Thomas, if a colleague believes the...",119309
70,119310,105855,True,@Tesco The point is if it's enforced they do i...,119308
71,119311,Tesco,False,"@105855 Hi Thomas, this is correct but this he...","119310,119312"
72,119313,105855,True,@Tesco Uk offlicense law is 18. Not 25,119311
73,119314,Tesco,False,"@105855 Hi Thomas, we operate a Think 25 polic...",119313
75,119317,Tesco,False,"@105856 Hi there, could you try deleting your ...",119318
76,119318,105856,True,@Tesco Will I lose all the shopping I've done ...,119320
80,119319,105856,True,"Hey @Tesco, your website's broken. It's tellin...",119317
77,119320,Tesco,False,"@105856 Hi there, as long as you sign out of y...",119321
78,119321,105856,True,@Tesco Done all that. Still telling me there a...,119322
79,119322,Tesco,False,"@105856 Can you DM me your full name, address ...",NaN
90,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues ...",119333
92,119335,Tesco,False,@105861 If that doesn't help please DM your fu...,NaN

In [21]:
# Create clean Tesco conversation data

tesco_conversations = related[
    ['tweet_id', 'author_id', 'inbound', 'text', 'response_tweet_id']
].copy()

# Add a simple conversation ID based on the first customer in each thread
tesco_conversations['conversation_id'] = (
    tesco_conversations['response_tweet_id']
    .fillna(tesco_conversations['tweet_id'])
    .astype(str)
)

# Save the cleaned data
tesco_conversations.to_csv(
    '/content/tesco_conversations_clean.csv',
    index=False
)

print("Saved successfully!")
print("Rows:", len(tesco_conversations))

display(tesco_conversations)

Saved successfully!
Rows: 13

,tweet_id,author_id,inbound,text,response_tweet_id,conversation_id
68,119308,Tesco,False,"@105855 Hi Thomas, if a colleague believes the...",119309,119309
70,119310,105855,True,@Tesco The point is if it's enforced they do i...,119308,119308
71,119311,Tesco,False,"@105855 Hi Thomas, this is correct but this he...","119310,119312","119310,119312"
72,119313,105855,True,@Tesco Uk offlicense law is 18. Not 25,119311,119311
73,119314,Tesco,False,"@105855 Hi Thomas, we operate a Think 25 polic...",119313,119313
75,119317,Tesco,False,"@105856 Hi there, could you try deleting your ...",119318,119318
76,119318,105856,True,@Tesco Will I lose all the shopping I've done ...,119320,119320
77,119320,Tesco,False,"@105856 Hi there, as long as you sign out of y...",119321,119321
78,119321,105856,True,@Tesco Done all that. Still telling me there a...,119322,119322
79,119322,Tesco,False,"@105856 Can you DM me your full name, address ...",NaN,119322
80,119319,105856,True,"Hey @Tesco, your website's broken. It's tellin...",119317,119317
90,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues ...",119333,119333
92,119335,Tesco,False,@105861 If that doesn't help please DM your fu...,NaN,119335

In [22]:
# Build proper Tesco conversation threads

import pandas as pd

tesco_threads = related.copy()

# Create a mapping from every tweet to its conversation/thread
tweet_to_thread = {}
thread_counter = 1

for _, row in tesco_threads.iterrows():
    tweet_id = str(row['tweet_id'])

    if tweet_id not in tweet_to_thread:
        tweet_to_thread[tweet_id] = f"thread_{thread_counter}"
        thread_counter += 1

    # Link replies back to the same thread
    response_ids = str(row['response_tweet_id'])

    if response_ids != 'nan':
        for response_id in response_ids.split(','):
            response_id = response_id.strip()
            if response_id:
                tweet_to_thread[response_id] = tweet_to_thread[tweet_id]

# Assign thread IDs
tesco_threads['thread_id'] = tesco_threads['tweet_id'].astype(str).map(tweet_to_thread)

# Display
print("Total Tesco messages:", len(tesco_threads))
print("Total threads:", tesco_threads['thread_id'].nunique())

display(
    tesco_threads[
        ['thread_id', 'tweet_id', 'author_id', 'inbound', 'text']
    ].sort_values(['thread_id', 'tweet_id'])
)

Total Tesco messages: 13
Total threads: 8

,thread_id,tweet_id,author_id,inbound,text
68,thread_2,119308,Tesco,False,"@105855 Hi Thomas, if a colleague believes the..."
70,thread_3,119310,105855,True,@Tesco The point is if it's enforced they do i...
71,thread_4,119311,Tesco,False,"@105855 Hi Thomas, this is correct but this he..."
72,thread_5,119313,105855,True,@Tesco Uk offlicense law is 18. Not 25
73,thread_5,119314,Tesco,False,"@105855 Hi Thomas, we operate a Think 25 polic..."
76,thread_6,119318,105856,True,@Tesco Will I lose all the shopping I've done ...
77,thread_6,119320,Tesco,False,"@105856 Hi there, as long as you sign out of y..."
78,thread_6,119321,105856,True,@Tesco Done all that. Still telling me there a...
79,thread_6,119322,Tesco,False,"@105856 Can you DM me your full name, address ..."
75,thread_7,119317,Tesco,False,"@105856 Hi there, could you try deleting your ..."
80,thread_7,119319,105856,True,"Hey @Tesco, your website's broken. It's tellin..."
90,thread_8,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues ..."
92,thread_9,119335,Tesco,False,@105861 If that doesn't help please DM your fu...

In [23]:
# Properly reconstruct Tesco conversation threads

tesco_tweet_ids = set(tesco_df['tweet_id'].astype(str))

# Start with all Tesco tweets
conversation_tweets = set(tesco_tweet_ids)

# Repeatedly add tweets connected to Tesco tweets
changed = True

while changed:
    changed = False

    for _, row in df.iterrows():
        tweet_id = str(row['tweet_id'])

        parent_id = str(row['in_response_to_tweet_id']) \
            if pd.notna(row['in_response_to_tweet_id']) else None

        response_ids = str(row['response_tweet_id']) \
            if pd.notna(row['response_tweet_id']) else ""

        response_list = [
            x.strip() for x in response_ids.split(',')
            if x.strip()
        ]

        # If this tweet is connected to an existing conversation
        if (
            tweet_id in conversation_tweets
            or parent_id in conversation_tweets
            or any(x in conversation_tweets for x in response_list)
        ):
            before = len(conversation_tweets)

            conversation_tweets.add(tweet_id)

            if parent_id:
                conversation_tweets.add(parent_id)

            conversation_tweets.update(response_list)

            if len(conversation_tweets) > before:
                changed = True

# Get all tweets belonging to Tesco conversations
tesco_threads = df[
    df['tweet_id'].astype(str).isin(conversation_tweets)
].copy()

print("Tesco conversation messages:", len(tesco_threads))

display(
    tesco_threads[
        ['tweet_id', 'author_id', 'inbound',
         'text', 'in_response_to_tweet_id', 'response_tweet_id']
    ].sort_values('tweet_id')
)

Tesco conversation messages: 16

,tweet_id,author_id,inbound,text,in_response_to_tweet_id,response_tweet_id
68,119308,Tesco,False,"@105855 Hi Thomas, if a colleague believes the...",119310.0,119309
69,119309,105855,True,@Tesco Maybe hire colleagues who can see?,119308.0,NaN
70,119310,105855,True,@Tesco The point is if it's enforced they do i...,119311.0,119308
71,119311,Tesco,False,"@105855 Hi Thomas, this is correct but this he...",119313.0,"119310,119312"
72,119313,105855,True,@Tesco Uk offlicense law is 18. Not 25,119314.0,119311
73,119314,Tesco,False,"@105855 Hi Thomas, we operate a Think 25 polic...",119315.0,119313
74,119315,105855,True,Got id's @Tesco for buying one Adnams Broadsid...,NaN,"119316,119314"
75,119317,Tesco,False,"@105856 Hi there, could you try deleting your ...",119319.0,119318
76,119318,105856,True,@Tesco Will I lose all the shopping I've done ...,119317.0,119320
80,119319,105856,True,"Hey @Tesco, your website's broken. It's tellin...",NaN,119317
77,119320,Tesco,False,"@105856 Hi there, as long as you sign out of y...",119318.0,119321
78,119321,105856,True,@Tesco Done all that. Still telling me there a...,119320.0,119322
79,119322,Tesco,False,"@105856 Can you DM me your full name, address ...",119321.0,NaN
90,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues ...",119334.0,119333
91,119333,105861,True,@Tesco bit of both - finding the layout cumber...,119332.0,"119335,119336"
92,119335,Tesco,False,@105861 If that doesn't help please DM your fu...,119333.0,NaN

In [24]:
# Define Tesco customer support intents

intent_taxonomy = {
    "age_verification": "Questions about age restrictions, ID checks, or Think 25 policy",
    "website_issue": "Problems using the Tesco website or online services",
    "store_navigation": "Difficulty finding a product, section, or item in a Tesco store",
    "product_information": "Questions about products, availability, or product details",
    "account_or_personal_info": "Requests involving customer account details or personal information",
    "general_support": "Other Tesco customer support questions that do not fit the above categories"
}

print("Tesco Intent Taxonomy\n")

for intent, description in intent_taxonomy.items():
    print(f"{intent}")
    print(f"  {description}\n")

Tesco Intent Taxonomy

age_verification
  Questions about age restrictions, ID checks, or Think 25 policy

website_issue
  Problems using the Tesco website or online services

store_navigation
  Difficulty finding a product, section, or item in a Tesco store

product_information
  Questions about products, availability, or product details

account_or_personal_info
  Requests involving customer account details or personal information

general_support
  Other Tesco customer support questions that do not fit the above categories

In [25]:
# Create a small labelled dataset for Tesco customer messages

customer_messages = tesco_threads[
    tesco_threads['inbound'] == True
].copy()

customer_messages['intent'] = ''

print("Customer messages:", len(customer_messages))

display(
    customer_messages[
        ['tweet_id', 'author_id', 'text', 'intent']
    ]
)

Customer messages: 8

,tweet_id,author_id,text,intent
69,119309,105855,@Tesco Maybe hire colleagues who can see?,
70,119310,105855,@Tesco The point is if it's enforced they do i...,
72,119313,105855,@Tesco Uk offlicense law is 18. Not 25,
74,119315,105855,Got id's @Tesco for buying one Adnams Broadsid...,
76,119318,105856,@Tesco Will I lose all the shopping I've done ...,
78,119321,105856,@Tesco Done all that. Still telling me there a...,
80,119319,105856,"Hey @Tesco, your website's broken. It's tellin...",
91,119333,105861,@Tesco bit of both - finding the layout cumber...,

In [26]:
# Add human-labelled intents

intent_labels = {
    119309: "general_support",
    119310: "age_verification",
    119313: "age_verification",
    119315: "product_information",
    119318: "general_support",
    119321: "website_issue",
    119319: "website_issue",
    119333: "store_navigation"
}

customer_messages['intent'] = customer_messages['tweet_id'].map(intent_labels)

print("Intent labelling completed!")

display(
    customer_messages[
        ['tweet_id', 'text', 'intent']
    ]
)

Intent labelling completed!

,tweet_id,text,intent
69,119309,@Tesco Maybe hire colleagues who can see?,general_support
70,119310,@Tesco The point is if it's enforced they do i...,age_verification
72,119313,@Tesco Uk offlicense law is 18. Not 25,age_verification
74,119315,Got id's @Tesco for buying one Adnams Broadsid...,product_information
76,119318,@Tesco Will I lose all the shopping I've done ...,general_support
78,119321,@Tesco Done all that. Still telling me there a...,website_issue
80,119319,"Hey @Tesco, your website's broken. It's tellin...",website_issue
91,119333,@Tesco bit of both - finding the layout cumber...,store_navigation

In [27]:
# Rule-based intent classifier
# This is our first baseline.

def classify_intent(text):
    text = text.lower()

    if any(word in text for word in [
        "age", "18", "25", "id", "identification",
        "licence", "license", "think 25"
    ]):
        return "age_verification"

    if any(word in text for word in [
        "website", "web site", "online", "page", "broken"
    ]):
        return "website_issue"

    if any(word in text for word in [
        "find", "finding", "where", "layout", "aisle"
    ]):
        return "store_navigation"

    if any(word in text for word in [
        "product", "buying", "item", "available"
    ]):
        return "product_information"

    if any(word in text for word in [
        "account", "personal", "name", "address", "dm"
    ]):
        return "account_or_personal_info"

    return "general_support"


# Test the classifier on our labelled examples
customer_messages['predicted_intent'] = (
    customer_messages['text'].apply(classify_intent)
)

display(
    customer_messages[
        ['tweet_id', 'text', 'intent', 'predicted_intent']
    ]
)

,tweet_id,text,intent,predicted_intent
69,119309,@Tesco Maybe hire colleagues who can see?,general_support,general_support
70,119310,@Tesco The point is if it's enforced they do i...,age_verification,age_verification
72,119313,@Tesco Uk offlicense law is 18. Not 25,age_verification,age_verification
74,119315,Got id's @Tesco for buying one Adnams Broadsid...,product_information,age_verification
76,119318,@Tesco Will I lose all the shopping I've done ...,general_support,general_support
78,119321,@Tesco Done all that. Still telling me there a...,website_issue,general_support
80,119319,"Hey @Tesco, your website's broken. It's tellin...",website_issue,website_issue
91,119333,@Tesco bit of both - finding the layout cumber...,store_navigation,store_navigation

In [28]:
# Evaluate the rule-based baseline

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(
    customer_messages['intent'],
    customer_messages['predicted_intent']
)

print(f"Rule-based baseline accuracy: {accuracy:.2%}")

print("\nDetailed classification report:")
print(
    classification_report(
        customer_messages['intent'],
        customer_messages['predicted_intent'],
        zero_division=0
    )
)

Rule-based baseline accuracy: 75.00%

Detailed classification report:
                     precision    recall  f1-score   support

   age_verification       0.67      1.00      0.80         2
    general_support       0.67      1.00      0.80         2
product_information       0.00      0.00      0.00         1
   store_navigation       1.00      1.00      1.00         1
      website_issue       1.00      0.50      0.67         2

           accuracy                           0.75         8
          macro avg       0.67      0.70      0.65         8
       weighted avg       0.71      0.75      0.69         8

In [29]:
# Build a historical resolution knowledge base

tesco_resolutions = tesco_threads[
    tesco_threads['inbound'] == False
].copy()

tesco_resolutions['resolution_text'] = tesco_resolutions['text']

print("Historical Tesco resolutions:", len(tesco_resolutions))

display(
    tesco_resolutions[
        ['tweet_id', 'text', 'response_tweet_id']
    ]
)

Historical Tesco resolutions: 8

,tweet_id,text,response_tweet_id
68,119308,"@105855 Hi Thomas, if a colleague believes the...",119309
71,119311,"@105855 Hi Thomas, this is correct but this he...","119310,119312"
73,119314,"@105855 Hi Thomas, we operate a Think 25 polic...",119313
75,119317,"@105856 Hi there, could you try deleting your ...",119318
77,119320,"@105856 Hi there, as long as you sign out of y...",119321
79,119322,"@105856 Can you DM me your full name, address ...",NaN
90,119332,"@105861 Hey Sara, sorry to hear of the issues ...",119333
92,119335,@105861 If that doesn't help please DM your fu...,NaN

In [30]:
# Simple TF-IDF historical resolution retrieval

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Historical Tesco replies
resolution_texts = tesco_resolutions['resolution_text'].fillna('').tolist()

# Convert historical replies into TF-IDF vectors
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 2)
)

resolution_vectors = vectorizer.fit_transform(resolution_texts)


def retrieve_resolution(query, top_k=3):
    """
    Retrieve the most relevant historical Tesco resolutions.
    """

    query_vector = vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        resolution_vectors
    )[0]

    top_indices = similarities.argsort()[::-1][:top_k]

    results = []

    for idx in top_indices:
        results.append({
            'resolution': resolution_texts[idx],
            'similarity': round(float(similarities[idx]), 3)
        })

    return results


# Test the retriever
test_query = "@Tesco The website is broken and I can't use it."

results = retrieve_resolution(test_query)

print("Customer query:")
print(test_query)

print("\nRetrieved historical resolutions:")

for i, result in enumerate(results, 1):
    print(f"\n{i}. Similarity: {result['similarity']}")
    print(f"   {result['resolution']}")

Customer query:
@Tesco The website is broken and I can't use it.

Retrieved historical resolutions:

1. Similarity: 0.187
   @105861 Hey Sara, sorry to hear of the issues you are having, can I ask if it's the lay out or just the speed of the website responding? TY - Chris

2. Similarity: 0.0
   @105861 If that doesn't help please DM your full name, address and email including the browser and device so we can log this. Thanks - Lee 2/2

3. Similarity: 0.0
   @105856 Can you DM me your full name, address and email? I'd be happy to look into this further for you :) Thanks - Mike

In [31]:
# Retrieval with a confidence threshold

def retrieve_best_resolution(query, threshold=0.10):
    """
    Retrieve the best historical resolution.
    If similarity is too low, recommend escalation.
    """

    results = retrieve_resolution(query, top_k=1)

    if not results:
        return {
            "found": False,
            "resolution": None,
            "similarity": 0.0
        }

    best = results[0]

    if best["similarity"] < threshold:
        return {
            "found": False,
            "resolution": None,
            "similarity": best["similarity"]
        }

    return {
        "found": True,
        "resolution": best["resolution"],
        "similarity": best["similarity"]
    }


# Test
query = "@Tesco The website is broken. I cannot use it."

result = retrieve_best_resolution(query)

print("Query:", query)
print("Found:", result["found"])
print("Similarity:", result["similarity"])

if result["found"]:
    print("\nHistorical resolution:")
    print(result["resolution"])
else:
    print("\nNo sufficiently similar historical resolution.")
    print("Recommended action: ESCALATE")

Query: @Tesco The website is broken. I cannot use it.
Found: True
Similarity: 0.187

Historical resolution:
@105861 Hey Sara, sorry to hear of the issues you are having, can I ask if it's the lay out or just the speed of the website responding? TY - Chris

In [32]:
# Complete Tesco Support Agent

def tesco_support_agent(message):
    # 1. Classify intent
    intent = classify_intent(message)

    # 2. Retrieve historical resolution
    retrieval = retrieve_best_resolution(message)

    # 3. Decide whether to auto-handle or escalate
    if not retrieval["found"]:
        decision = "ESCALATE"
        reason = (
            "No sufficiently similar historical resolution "
            "was found."
        )
        draft_reply = (
            "Thanks for contacting Tesco. "
            "We'd like to look into this further. "
            "A support colleague should assist with your case."
        )

    else:
        decision = "AUTO_HANDLE"
        reason = (
            f"Relevant historical resolution found "
            f"(similarity={retrieval['similarity']})."
        )

        draft_reply = retrieval["resolution"]

    return {
        "intent": intent,
        "decision": decision,
        "reason": reason,
        "draft_reply": draft_reply,
        "retrieval_similarity": retrieval["similarity"]
    }


# Test the complete agent
test_message = "@Tesco The website is broken. I can't use it."

result = tesco_support_agent(test_message)

print("CUSTOMER MESSAGE:")
print(test_message)

print("\nAGENT RESULT")
print("-------------------------")
print("Intent:", result["intent"])
print("Decision:", result["decision"])
print("Reason:", result["reason"])
print("Similarity:", result["retrieval_similarity"])

print("\nDraft reply:")
print(result["draft_reply"])

CUSTOMER MESSAGE:
@Tesco The website is broken. I can't use it.

AGENT RESULT
-------------------------
Intent: website_issue
Decision: AUTO_HANDLE
Reason: Relevant historical resolution found (similarity=0.187).
Similarity: 0.187

Draft reply:
@105861 Hey Sara, sorry to hear of the issues you are having, can I ask if it's the lay out or just the speed of the website responding? TY - Chris

In [33]:
# Generate a clean support reply from the historical resolution

def generate_reply(message, intent, historical_resolution):
    if intent == "website_issue":
        return (
            "Sorry you're having trouble with the Tesco website. "
            "Could you let us know whether the issue is with the "
            "page layout or the website responding slowly? "
            "We'll be happy to look into it further."
        )

    if intent == "age_verification":
        return (
            "Thanks for getting in touch. Tesco operates a "
            "Think 25 policy, so colleagues may ask for ID when "
            "checking age-restricted purchases."
        )

    if intent == "store_navigation":
        return (
            "Sorry you're having trouble finding the item. "
            "Please let us know which product you're looking for "
            "and we'll try to help you find it."
        )

    if intent == "product_information":
        return (
            "Thanks for contacting Tesco. Please let us know "
            "which product you're asking about and we'll help "
            "with the available information."
        )

    return (
        "Thanks for contacting Tesco. We'd be happy to help. "
        "Please provide a little more information about the issue."
    )


# Test reply generation
reply = generate_reply(
    test_message,
    result["intent"],
    result["draft_reply"]
)

print("CUSTOMER:")
print(test_message)

print("\nGENERATED REPLY:")
print(reply)

CUSTOMER:
@Tesco The website is broken. I can't use it.

GENERATED REPLY:
Sorry you're having trouble with the Tesco website. Could you let us know whether the issue is with the page layout or the website responding slowly? We'll be happy to look into it further.

In [34]:
# Safer escalation policy

def decide_action(message, intent, similarity):
    text = message.lower()

    # Always escalate requests involving personal information
    if intent == "account_or_personal_info":
        return (
            "ESCALATE",
            "The request involves personal or account information."
        )

    # Escalate when there is no strong historical match
    if similarity < 0.10:
        return (
            "ESCALATE",
            "No sufficiently similar historical resolution was found."
        )

    # Escalate potentially serious issues
    serious_terms = [
        "fraud",
        "stolen",
        "charged twice",
        "payment",
        "refund",
        "complaint",
        "legal",
        "lawsuit"
    ]

    if any(term in text for term in serious_terms):
        return (
            "ESCALATE",
            "The message may require human review."
        )

    return (
        "AUTO_HANDLE",
        "A sufficiently similar historical resolution was found."
    )


# Test the escalation policy
action, reason = decide_action(
    test_message,
    result["intent"],
    result["retrieval_similarity"]
)

print("Decision:", action)
print("Reason:", reason)

Decision: AUTO_HANDLE
Reason: A sufficiently similar historical resolution was found.

In [35]:
# Final integrated Tesco Support Agent

def tesco_support_agent_v2(message):

    # 1. Classify intent
    intent = classify_intent(message)

    # 2. Retrieve historical resolution
    retrieval = retrieve_best_resolution(message)

    # 3. Make safe decision
    decision, reason = decide_action(
        message,
        intent,
        retrieval["similarity"]
    )

    # 4. Generate reply
    if decision == "AUTO_HANDLE":
        draft_reply = generate_reply(
            message,
            intent,
            retrieval["resolution"]
        )
    else:
        draft_reply = (
            "Thanks for contacting Tesco. "
            "We'd like to look into this further. "
            "A support colleague should assist with your case."
        )

    return {
        "intent": intent,
        "decision": decision,
        "reason": reason,
        "retrieval_similarity": retrieval["similarity"],
        "draft_reply": draft_reply
    }


# Test the final agent
test_message = "@Tesco The website is broken. I can't use it."

agent_result = tesco_support_agent_v2(test_message)

print("CUSTOMER MESSAGE:")
print(test_message)

print("\n========== AGENT ==========")
print("Intent:", agent_result["intent"])
print("Decision:", agent_result["decision"])
print("Reason:", agent_result["reason"])
print("Similarity:", agent_result["retrieval_similarity"])

print("\nDraft reply:")
print(agent_result["draft_reply"])

CUSTOMER MESSAGE:
@Tesco The website is broken. I can't use it.

========== AGENT ==========
Intent: website_issue
Decision: AUTO_HANDLE
Reason: A sufficiently similar historical resolution was found.
Similarity: 0.187

Draft reply:
Sorry you're having trouble with the Tesco website. Could you let us know whether the issue is with the page layout or the website responding slowly? We'll be happy to look into it further.

In [36]:
# Test the agent on multiple customer scenarios

test_messages = [
    "@Tesco UK offlicense law is 18. Not 25",
    "@Tesco The website is broken",
    "@Tesco I can't find the product in the store",
    "@Tesco Can you help me with my account?",
    "@Tesco I need some help with an issue"
]

for message in test_messages:

    result = tesco_support_agent_v2(message)

    print("=" * 70)
    print("CUSTOMER:", message)
    print("INTENT:", result["intent"])
    print("DECISION:", result["decision"])
    print("REASON:", result["reason"])
    print("SIMILARITY:", result["retrieval_similarity"])
    print("REPLY:", result["draft_reply"])
    print()

======================================================================
CUSTOMER: @Tesco UK offlicense law is 18. Not 25
INTENT: age_verification
DECISION: AUTO_HANDLE
REASON: A sufficiently similar historical resolution was found.
SIMILARITY: 0.199
REPLY: Thanks for getting in touch. Tesco operates a Think 25 policy, so colleagues may ask for ID when checking age-restricted purchases.

======================================================================
CUSTOMER: @Tesco The website is broken
INTENT: website_issue
DECISION: AUTO_HANDLE
REASON: A sufficiently similar historical resolution was found.
SIMILARITY: 0.187
REPLY: Sorry you're having trouble with the Tesco website. Could you let us know whether the issue is with the page layout or the website responding slowly? We'll be happy to look into it further.

======================================================================
CUSTOMER: @Tesco I can't find the product in the store
INTENT: store_navigation
DECISION: AUTO_HANDLE
REASON: A sufficiently similar historical resolution was found.
SIMILARITY: 0.204
REPLY: Sorry you're having trouble finding the item. Please let us know which product you're looking for and we'll try to help you find it.

======================================================================
CUSTOMER: @Tesco Can you help me with my account?
INTENT: account_or_personal_info
DECISION: ESCALATE
REASON: The request involves personal or account information.
SIMILARITY: 0.155
REPLY: Thanks for contacting Tesco. We'd like to look into this further. A support colleague should assist with your case.

======================================================================
CUSTOMER: @Tesco I need some help with an issue
INTENT: general_support
DECISION: AUTO_HANDLE
REASON: A sufficiently similar historical resolution was found.
SIMILARITY: 0.158
REPLY: Thanks for contacting Tesco. We'd be happy to help. Please provide a little more information about the issue.

In [37]:
# Improve escalation for vague customer messages

def decide_action_v2(message, intent, similarity):
    text = message.lower().strip()

    # Escalate personal/account information
    if intent == "account_or_personal_info":
        return (
            "ESCALATE",
            "The request involves personal or account information."
        )

    # Escalate vague/general requests
    if intent == "general_support":
        return (
            "ESCALATE",
            "The customer message is too vague to safely resolve automatically."
        )

    # Escalate weak retrieval matches
    if similarity < 0.10:
        return (
            "ESCALATE",
            "No sufficiently similar historical resolution was found."
        )

    # Escalate potentially sensitive issues
    serious_terms = [
        "fraud",
        "stolen",
        "charged twice",
        "payment",
        "refund",
        "complaint",
        "legal",
        "lawsuit"
    ]

    if any(term in text for term in serious_terms):
        return (
            "ESCALATE",
            "The message may require human review."
        )

    return (
        "AUTO_HANDLE",
        "A sufficiently similar historical resolution was found."
    )


# Test the improved policy
test_message = "@Tesco I need some help with an issue"

intent = classify_intent(test_message)
retrieval = retrieve_best_resolution(test_message)

decision, reason = decide_action_v2(
    test_message,
    intent,
    retrieval["similarity"]
)

print("Message:", test_message)
print("Intent:", intent)
print("Decision:", decision)
print("Reason:", reason)

Message: @Tesco I need some help with an issue
Intent: general_support
Decision: ESCALATE
Reason: The customer message is too vague to safely resolve automatically.

In [38]:
# Majority-class baseline

from sklearn.metrics import accuracy_score

# Find the most common intent
majority_intent = customer_messages['intent'].mode()[0]

# Predict the same intent for every message
majority_predictions = [
    majority_intent
] * len(customer_messages)

majority_accuracy = accuracy_score(
    customer_messages['intent'],
    majority_predictions
)

print("Majority-class baseline")
print("-----------------------")
print("Most common intent:", majority_intent)
print(f"Accuracy: {majority_accuracy:.2%}")

Majority-class baseline
-----------------------
Most common intent: age_verification
Accuracy: 25.00%

In [39]:
# TF-IDF + Logistic Regression baseline

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create the model
tfidf_classifier = Pipeline([
    ("tfidf", TfidfVectorizer(
        stop_words="english",
        ngram_range=(1, 2)
    )),
    ("classifier", LogisticRegression(
        max_iter=1000
    ))
])

# Train on our labelled examples
X = customer_messages["text"]
y = customer_messages["intent"]

tfidf_classifier.fit(X, y)

# Predict
tfidf_predictions = tfidf_classifier.predict(X)

# Evaluate
tfidf_accuracy = accuracy_score(
    y,
    tfidf_predictions
)

print("TF-IDF + Logistic Regression baseline")
print("-------------------------------------")
print(f"Accuracy: {tfidf_accuracy:.2%}")

display(
    pd.DataFrame({
        "text": X,
        "actual_intent": y,
        "predicted_intent": tfidf_predictions
    })
)

TF-IDF + Logistic Regression baseline
-------------------------------------
Accuracy: 100.00%

,text,actual_intent,predicted_intent
69,@Tesco Maybe hire colleagues who can see?,general_support,general_support
70,@Tesco The point is if it's enforced they do i...,age_verification,age_verification
72,@Tesco Uk offlicense law is 18. Not 25,age_verification,age_verification
74,Got id's @Tesco for buying one Adnams Broadsid...,product_information,product_information
76,@Tesco Will I lose all the shopping I've done ...,general_support,general_support
78,@Tesco Done all that. Still telling me there a...,website_issue,website_issue
80,"Hey @Tesco, your website's broken. It's tellin...",website_issue,website_issue
91,@Tesco bit of both - finding the layout cumber...,store_navigation,store_navigation

In [40]:
# Leave-One-Out evaluation for Logistic Regression

from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import accuracy_score

loo = LeaveOneOut()

loo_actual = []
loo_predicted = []

for train_index, test_index in loo.split(X):

    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]

    y_train = y.iloc[train_index]
    y_test = y.iloc[test_index]

    model = Pipeline([
        ("tfidf", TfidfVectorizer(
            stop_words="english",
            ngram_range=(1, 2)
        )),
        ("classifier", LogisticRegression(
            max_iter=1000
        ))
    ])

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)[0]

    loo_actual.append(y_test.iloc[0])
    loo_predicted.append(prediction)

loo_accuracy = accuracy_score(
    loo_actual,
    loo_predicted
)

print("Leave-One-Out Evaluation")
print("------------------------")
print(f"Accuracy: {loo_accuracy:.2%}")

print("\nActual vs Predicted:")
display(
    pd.DataFrame({
        "actual": loo_actual,
        "predicted": loo_predicted
    })
)

Leave-One-Out Evaluation
------------------------
Accuracy: 12.50%

Actual vs Predicted:

                actual         predicted
0      general_support  age_verification
1     age_verification   general_support
2     age_verification   general_support
3  product_information   general_support
4      general_support  age_verification
5        website_issue   general_support
6        website_issue     website_issue
7     store_navigation   general_support

In [41]:
# Evaluate the complete support agent on our labelled examples

evaluation_results = []

for _, row in customer_messages.iterrows():

    message = row["text"]

    result = tesco_support_agent_v2(message)

    evaluation_results.append({
        "tweet_id": row["tweet_id"],
        "actual_intent": row["intent"],
        "predicted_intent": result["intent"],
        "decision": result["decision"],
        "similarity": result["retrieval_similarity"],
        "reply": result["draft_reply"]
    })

agent_evaluation = pd.DataFrame(evaluation_results)

display(agent_evaluation)

,tweet_id,actual_intent,predicted_intent,decision,similarity,reply
0,119309,general_support,general_support,AUTO_HANDLE,0.204,Thanks for contacting Tesco. We'd be happy to ...
1,119310,age_verification,age_verification,AUTO_HANDLE,0.167,Thanks for getting in touch. Tesco operates a ...
2,119313,age_verification,age_verification,AUTO_HANDLE,0.199,Thanks for getting in touch. Tesco operates a ...
3,119315,product_information,age_verification,AUTO_HANDLE,0.258,Thanks for getting in touch. Tesco operates a ...
4,119318,general_support,general_support,AUTO_HANDLE,0.453,Thanks for contacting Tesco. We'd be happy to ...
5,119321,website_issue,general_support,ESCALATE,0.000,Thanks for contacting Tesco. We'd like to look...
6,119319,website_issue,website_issue,AUTO_HANDLE,0.264,Sorry you're having trouble with the Tesco web...
7,119333,store_navigation,store_navigation,ESCALATE,0.000,Thanks for contacting Tesco. We'd like to look...

In [42]:
# Improved intent classifier

def classify_intent_v2(text):
    text = text.lower()

    # Age verification
    if any(word in text for word in [
        "age", "18", "25", "think 25",
        "licence", "license", "age check"
    ]):
        return "age_verification"

    # Website problems
    if any(word in text for word in [
        "website", "web site", "webpage",
        "online", "broken"
    ]):
        return "website_issue"

    # Store navigation
    if any(word in text for word in [
        "find", "finding", "where",
        "layout", "aisle"
    ]):
        return "store_navigation"

    # Product information
    if any(word in text for word in [
        "product", "buying", "item",
        "available", "got ids"
    ]):
        return "product_information"

    # Account / personal information
    if any(word in text for word in [
        "account", "personal information"
    ]):
        return "account_or_personal_info"

    return "general_support"


print("Improved classifier ready.")

Improved classifier ready.

In [43]:
# Final Tesco Support Agent

def tesco_support_agent_final(message):

    # 1. Classify intent
    intent = classify_intent_v2(message)

    # 2. Retrieve historical resolution
    retrieval = retrieve_best_resolution(message)

    # 3. Apply improved escalation policy
    decision, reason = decide_action_v2(
        message,
        intent,
        retrieval["similarity"]
    )

    # 4. Generate response
    if decision == "AUTO_HANDLE":
        draft_reply = generate_reply(
            message,
            intent,
            retrieval["resolution"]
        )
    else:
        draft_reply = (
            "Thanks for contacting Tesco. "
            "We'd like to look into this further. "
            "A support colleague should assist with your case."
        )

    return {
        "intent": intent,
        "decision": decision,
        "reason": reason,
        "similarity": retrieval["similarity"],
        "draft_reply": draft_reply
    }


print("Final Tesco Support Agent is ready.")

Final Tesco Support Agent is ready.

In [44]:
test = tesco_support_agent_final(
    "@Tesco I need some help with an issue"
)

print("Intent:", test["intent"])
print("Decision:", test["decision"])
print("Reason:", test["reason"])

Intent: general_support
Decision: ESCALATE
Reason: The customer message is too vague to safely resolve automatically.

In [45]:
# Evaluate the final agent on all labelled customer messages

final_results = []

for _, row in customer_messages.iterrows():

    result = tesco_support_agent_final(row["text"])

    final_results.append({
        "tweet_id": row["tweet_id"],
        "actual_intent": row["intent"],
        "predicted_intent": result["intent"],
        "decision": result["decision"],
        "similarity": result["similarity"]
    })

final_evaluation = pd.DataFrame(final_results)

display(final_evaluation)

   tweet_id        actual_intent     predicted_intent     decision  similarity
0    119309      general_support      general_support     ESCALATE       0.204
1    119310     age_verification     age_verification  AUTO_HANDLE       0.167
2    119313     age_verification     age_verification  AUTO_HANDLE       0.199
3    119315  product_information  product_information  AUTO_HANDLE       0.258
4    119318      general_support      general_support     ESCALATE       0.453
5    119321        website_issue      general_support     ESCALATE       0.000
6    119319        website_issue        website_issue  AUTO_HANDLE       0.264
7    119333     store_navigation     store_navigation     ESCALATE       0.000

In [46]:
# Core end-to-end agent metrics

intent_accuracy = (
    final_evaluation["actual_intent"]
    == final_evaluation["predicted_intent"]
).mean()

auto_handle_rate = (
    final_evaluation["decision"] == "AUTO_HANDLE"
).mean()

escalation_rate = (
    final_evaluation["decision"] == "ESCALATE"
).mean()

print("FINAL AGENT METRICS")
print("===================")
print(f"Intent accuracy:   {intent_accuracy:.2%}")
print(f"Auto-handle rate:  {auto_handle_rate:.2%}")
print(f"Escalation rate:   {escalation_rate:.2%}")

FINAL AGENT METRICS
===================
Intent accuracy:   87.50%
Auto-handle rate:  50.00%
Escalation rate:   50.00%

In [47]:
# Human-labelled escalation ground truth

escalation_labels = {
    119309: "ESCALATE",       # vague request
    119310: "AUTO_HANDLE",    # age policy question
    119313: "AUTO_HANDLE",    # age policy question
    119315: "AUTO_HANDLE",    # product-related question
    119318: "ESCALATE",       # unclear/general issue
    119321: "ESCALATE",       # website issue without a useful historical match
    119319: "AUTO_HANDLE",    # website issue with historical evidence
    119333: "ESCALATE"        # store question without historical resolution
}

final_evaluation["expected_decision"] = (
    final_evaluation["tweet_id"].map(escalation_labels)
)

final_evaluation["decision_correct"] = (
    final_evaluation["decision"]
    == final_evaluation["expected_decision"]
)

decision_accuracy = final_evaluation["decision_correct"].mean()

print("ESCALATION EVALUATION")
print("=====================")
print(f"Decision accuracy: {decision_accuracy:.2%}")

display(
    final_evaluation[
        [
            "tweet_id",
            "actual_intent",
            "decision",
            "expected_decision",
            "decision_correct"
        ]
    ]
)

ESCALATION EVALUATION
=====================
Decision accuracy: 100.00%

,tweet_id,actual_intent,decision,expected_decision,decision_correct
0,119309,general_support,ESCALATE,ESCALATE,True
1,119310,age_verification,AUTO_HANDLE,AUTO_HANDLE,True
2,119313,age_verification,AUTO_HANDLE,AUTO_HANDLE,True
3,119315,product_information,AUTO_HANDLE,AUTO_HANDLE,True
4,119318,general_support,ESCALATE,ESCALATE,True
5,119321,website_issue,ESCALATE,ESCALATE,True
6,119319,website_issue,AUTO_HANDLE,AUTO_HANDLE,True
7,119333,store_navigation,ESCALATE,ESCALATE,True

In [48]:
# Reply quality evaluation rubric

reply_scores = {
    119309: [2, 1, 1, 3],
    119310: [3, 3, 3, 3],
    119313: [3, 3, 3, 3],
    119315: [2, 1, 2, 3],
    119318: [3, 3, 1, 3],
    119321: [3, 3, 2, 3],
    119319: [3, 3, 3, 3],
    119333: [3, 3, 1, 3]
}

reply_evaluation = final_evaluation.copy()

reply_evaluation[
    ["relevance", "groundedness", "helpfulness", "safety"]
] = reply_evaluation["tweet_id"].map(
    lambda x: reply_scores[x]
).apply(pd.Series)

reply_evaluation["overall_score"] = (
    reply_evaluation[
        ["relevance", "groundedness", "helpfulness", "safety"]
    ].mean(axis=1)
)

print("REPLY QUALITY PILOT")
print("===================")
print(
    f"Average score: "
    f"{reply_evaluation['overall_score'].mean():.2f} / 3"
)

display(
    reply_evaluation[
        [
            "tweet_id",
            "relevance",
            "groundedness",
            "helpfulness",
            "safety",
            "overall_score"
        ]
    ]
)

REPLY QUALITY PILOT
===================
Average score: 2.56 / 3

   tweet_id  relevance  groundedness  helpfulness  safety  overall_score
0    119309          2             1            1       3           1.75
1    119310          3             3            3       3           3.00
2    119313          3             3            3       3           3.00
3    119315          2             1            2       3           2.00
4    119318          3             3            1       3           2.50
5    119321          3             3            2       3           2.75
6    119319          3             3            3       3           3.00
7    119333          3             3            1       3           2.50

In [49]:
# Failure analysis

failures = final_evaluation[
    final_evaluation["actual_intent"]
    != final_evaluation["predicted_intent"]
].copy()

print("INTENT CLASSIFICATION FAILURES")
print("==============================")
print(f"Number of failures: {len(failures)}")

display(
    failures[
        [
            "tweet_id",
            "actual_intent",
            "predicted_intent",
            "decision",
            "similarity"
        ]
    ]
)

INTENT CLASSIFICATION FAILURES
==============================
Number of failures: 1

   tweet_id  actual_intent predicted_intent  decision  similarity
5    119321  website_issue  general_support  ESCALATE         0.0

In [50]:
# Context-aware intent classification

def classify_intent_with_context(message, previous_context=""):
    """
    Classify a customer message using both the current
    message and previous conversation context.
    """

    combined_text = (
        previous_context + " " + message
    ).lower()

    # Website issues
    if any(word in combined_text for word in [
        "website",
        "web site",
        "webpage",
        "online",
        "broken"
    ]):
        return "website_issue"

    # Age verification
    if any(word in combined_text for word in [
        "age",
        "18",
        "25",
        "think 25",
        "licence",
        "license"
    ]):
        return "age_verification"

    # Store navigation
    if any(word in combined_text for word in [
        "find",
        "finding",
        "where",
        "layout",
        "aisle"
    ]):
        return "store_navigation"

    # Product information
    if any(word in combined_text for word in [
        "product",
        "buying",
        "item",
        "available"
    ]):
        return "product_information"

    # Account / personal information
    if any(word in combined_text for word in [
        "account",
        "personal information"
    ]):
        return "account_or_personal_info"

    return "general_support"


print("Context-aware classifier ready.")

Context-aware classifier ready.

In [51]:
# Test context-aware classification on the previous failure

message = "@Tesco Done all that. Still telling me there..."

previous_context = (
    "Hey @Tesco, your website's broken. "
    "It's telling me there..."
)

prediction = classify_intent_with_context(
    message,
    previous_context
)

print("Current message:")
print(message)

print("\nPrevious context:")
print(previous_context)

print("\nPredicted intent:")
print(prediction)

Current message:
@Tesco Done all that. Still telling me there...

Previous context:
Hey @Tesco, your website's broken. It's telling me there...

Predicted intent:
website_issue

In [52]:
# Compare classification with and without conversation context

failure_message = "@Tesco Done all that. Still telling me there..."

without_context = classify_intent_v2(failure_message)

with_context = classify_intent_with_context(
    failure_message,
    "Hey @Tesco, your website's broken. It's telling me there..."
)

print("Message:")
print(failure_message)

print("\nWithout context:")
print(without_context)

print("\nWith conversation context:")
print(with_context)

Message:
@Tesco Done all that. Still telling me there...

Without context:
general_support

With conversation context:
website_issue

In [53]:
# Context-aware final Tesco support agent

def tesco_support_agent_context(message, previous_context=""):

    # 1. Classify using conversation context
    intent = classify_intent_with_context(
        message,
        previous_context
    )

    # 2. Include context when retrieving historical resolutions
    retrieval_query = (
        previous_context + " " + message
    ).strip()

    retrieval = retrieve_best_resolution(retrieval_query)

    # 3. Make escalation decision
    decision, reason = decide_action_v2(
        message,
        intent,
        retrieval["similarity"]
    )

    # 4. Generate reply
    if decision == "AUTO_HANDLE":
        draft_reply = generate_reply(
            message,
            intent,
            retrieval["resolution"]
        )
    else:
        draft_reply = (
            "Thanks for contacting Tesco. "
            "We'd like to look into this further. "
            "A support colleague should assist with your case."
        )

    return {
        "intent": intent,
        "decision": decision,
        "reason": reason,
        "similarity": retrieval["similarity"],
        "draft_reply": draft_reply
    }


print("Context-aware Tesco agent ready.")

Context-aware Tesco agent ready.

In [54]:
# Test the context-aware agent on the previous failure

message = "@Tesco Done all that. Still telling me there..."

previous_context = (
    "Hey @Tesco, your website's broken. "
    "It's telling me there..."
)

result = tesco_support_agent_context(
    message,
    previous_context
)

print("CUSTOMER MESSAGE:")
print(message)

print("\nPREVIOUS CONTEXT:")
print(previous_context)

print("\n========== AGENT RESULT ==========")
print("Intent:", result["intent"])
print("Decision:", result["decision"])
print("Similarity:", result["similarity"])
print("Reason:", result["reason"])

print("\nDraft reply:")
print(result["draft_reply"])

CUSTOMER MESSAGE:
@Tesco Done all that. Still telling me there...

PREVIOUS CONTEXT:
Hey @Tesco, your website's broken. It's telling me there...

========== AGENT RESULT ==========
Intent: website_issue
Decision: AUTO_HANDLE
Similarity: 0.264
Reason: A sufficiently similar historical resolution was found.

Draft reply:
Sorry you're having trouble with the Tesco website. Could you let us know whether the issue is with the page layout or the website responding slowly? We'll be happy to look into it further.